[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "2.2.1" 
solana-client = "2.2.1"
solana-program = "2.2.1"
borsh = "1.5.5"
anyhow = "1.0.97"

[[bin]]
name = "client"
path = "src/main.rs"

[[test]]
name = "test_program"
path = "src/test.rs"
