[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
solana-program = "2.1.11"
solana-sdk = "2.1.11"
solana-client = "2.1.11"
pinocchio_program = { path = "../program" }
borsh = "1.5.5"
borsh-derive = "1.5.5"

